---
version: "2.0"

services:
  node:
    image: elhachon/evmos-on-akash:v6.0.1-r2
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 1317
        to:
          - global: true
      - port: 8545
        to:
          - global: true

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 8
        memory:
          size: 64Gi
        storage:
          size: 500Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 1000

deployment:
  node:
    dcloud:
      profile: node
      count: 1
